pipeline {
  agent any

  stages {
   
   stage(‘clone project’) {
      steps {
           git branch:'master' , url:'https://github.com/PraveenKuberABC/Amazon-Ecom.git'
       }
   }

   stage('clean') {
      steps {
        echo "Running Clean Stage" 
           sh 'mvn clean'
       }
   }
  }
}
